### ISSUE TITLE
API url issues

### ISSUE THREAD

**Issue by drewskidang** [nlmatics/nlm-ingestor#22]
I'm having trouble using the custom url. When i use the example given it works fine but when using my own sever i get this issue json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(.conda) (base) root@LangLlama:~/wsl_projects/titan/nlm-ingestor# /root/wsl_projects/titan/nlm-ingestor/.conda/bin/python /root/wsl_projects/titan/nlm-ingestor/customrag.py
Traceback (most recent call last):
  File "/root/wsl_projects/titan/nlm-ingestor/customrag.py", line 47, in <module>
    process_pdfs(pdf_directory)
  File "/root/wsl_projects/titan/nlm-ingestor/customrag.py", line 17, in process_pdfs
    docs = pdf_reader.read_pdf(pdf_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/wsl_projects/titan/nlm-ingestor/.conda/lib/python3.11/site-packages/llmsherpa/readers/file_reader.py", line 73, in read_pdf
    blocks = response_json['return_dict']['result']['blocks']
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'
(.conda) (base) root@LangLlama:~/wsl_projects/titan/nlm-ingestor#

**Comment by jpbalarini** [comment]
Having the same issue on some files

**Comment by opiethehokie** [comment]
The llmsherpa code doesn't seem to handle nlm-ingestor errors well, so I think you'll see this error any time reading a PDF fails. You need to look at the Python server code, from run.sh the output of `python -m nlm_ingestor.ingestion_daemon` to see the specific nlm-ingestor error.

**Comment by siniya186** [comment]
any update on this issue?

**Comment by drewskidang** [comment]
@jpbalarini i ran the docker instead and had no issues :)
