### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by aman-vink** [nlmatics/nlm-ingestor#48]
KeyError                                  Traceback (most recent call last)
[<ipython-input-8-d7f1590b2867>](https://localhost:8080/#) in <cell line: 15>()
     13     llmsherpa_api_url = llmsherpa_api_url + "&applyOcr=yes"
     14 pdf_reader = LayoutPDFReader(llmsherpa_api_url)
---> 15 doc = pdf_reader.read_pdf(pdf_url)

[/usr/local/lib/python3.10/dist-packages/llmsherpa/readers/file_reader.py](https://localhost:8080/#) in read_pdf(self, path_or_url, contents)
     71         parser_response = self._parse_pdf(pdf_file)
     72         response_json = json.loads(parser_response.data.decode("utf-8"))
---> 73         blocks = response_json['return_dict']['result']['blocks']
     74         return Document(blocks)

KeyError: 'return_dict'

https://s201.q4cdn.com/262069030/files/doc_financials/2023/ar/Walmart-10K-Reports-Optimized.pdf

For this url

**Comment by kiran-nlmatics** [comment]
@aman-vink, Please pull from the main branch and let me know if the issue is still observed.

**Comment by erikbijl** [comment]
Same issue for me on a long pdf (>200 pages)

**Comment by almariscal** [comment]
Hello @kiran-nlmatics I am facing the same issue and just did pip install nlm-ingestor + LLM Sherpa docker server.

**Comment by madhuprakash19** [comment]
File "/Users/tpmpraka/miniconda3/envs/grm/lib/python3.11/site-packages/llmsherpa/readers/file_reader.py", line 74, in read_pdf
    blocks = response_json['return_dict']['result']['blocks']
             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'return_dict'


response JSON was {'reason': "'style'", 'status': 'fail'}

**Comment by bzhr** [comment]
I am also getting this error, any update on a fix?

**Comment by zmusaddique** [comment]
Getting the same error. A fix would be highly appreciated

**Comment by deepakdhiman7** [comment]
I am also getting the same error. Is it because of table format in PDF? I am attaching the docker logs below for debugging purpose:


`testing.. {'parse_and_render_only': True, 'render_format': 'all', 'use_new_indent_parser': False, 'parse_pages': (), 'apply_ocr': False}
processing page:  0  Number of p_tags....  63
processing page:  1  Number of p_tags....  44
processing page:  2  Number of p_tags....  131
processing page:  3  Number of p_tags....  121
processing page:  4  Number of p_tags....  189
processing page:  5  Number of p_tags....  120
processing page:  6  Number of p_tags....  218
processing page:  7  Number of p_tags....  179
processing page:  8  Number of p_tags....  144
processing page:  9  Number of p_tags....  129
processing page:  10  Number of p_tags....  109
processing page:  11  Number of p_tags....  99
processing page:  12  Number of p_tags....  64
processing page:  13  Number of p_tags....  115
error uploading file, stacktrace: Traceback (most recent call last):
  File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 44, in parse_document
    ingest_status, return_dict = ingestor_api.ingest_document(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 37, in ingest_document
    pdfi = pdf_ingestor.PDFIngestor(doc_location, parse_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 35, in __init__
    blocks, _block_texts, _sents, _file_data, result, page_dim, num_pages = parse_blocks(
                                                                            ^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 172, in parse_blocks
    parsed_doc = visual_ingestor.Doc(pages, ignore_blocks, render_format)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 117, in __init__
    self.parse(pages)
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 562, in parse
    self.json_dict = block_renderer.BlockRenderer(self).render_json()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/visual_ingestor/block_renderer.py", line 347, in render_json
    table_block["left"],
    ~~~~~~~~~~~^^^^^^^^
KeyError: 'left'
Traceback (most recent call last):
  File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 44, in parse_document
    ingest_status, return_dict = ingestor_api.ingest_document(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 37, in ingest_document
    pdfi = pdf_ingestor.PDFIngestor(doc_location, parse_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 35, in __init__
    blocks, _block_texts, _sents, _file_data, result, page_dim, num_pages = parse_blocks(
                                                                            ^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 172, in parse_blocks
    parsed_doc = visual_ingestor.Doc(pages, ignore_blocks, render_format)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 117, in __init__
    self.parse(pages)
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 562, in parse
    self.json_dict = block_renderer.BlockRenderer(self).render_json()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/visual_ingestor/block_renderer.py", line 347, in render_json
    table_block["left"],
    ~~~~~~~~~~~^^^^^^^^
KeyError: 'left'`

Thanks
Deepak

**Comment by singhkumaranuj** [comment]
Hi @kiran-nlmatics  is this issue fixed ?

**Comment by aashutosh-habile** [comment]
Hey @ansukla can you please let us know the solution?

**Comment by Redsed610** [comment]
I have also tried to find a fix for this, working with the latest version and also trying the old v.0.1.6 version, but no success. Would be grateful for a solution if anyone has one.

**Comment by lauriejohnstongentekai** [comment]
I have also received this error on the example document
