### ISSUE TITLE
KeyError: 'style'

### ISSUE THREAD

**Issue by RaphSte** [nlmatics/nlm-ingestor#72]
When trying to run a pdf file through it I get the KeyError: 'style', with the following stacktrace:   
   
```
error uploading file, stacktrace: Traceback (most recent call last):
  File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 48, in parse_document
    return_dict, _ = ingestor_api.ingest_document(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 37, in ingest_document
    ingestor = pdf_ingestor.PDFIngestor(doc_location, parse_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 35, in __init__
    blocks, _block_texts, _sents, _file_data, result, page_dim, num_pages = parse_blocks(
                                                                            ^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 176, in parse_blocks
    parsed_doc = visual_ingestor.Doc(pages, ignore_blocks, render_format)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 117, in __init__
    self.parse(pages)
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 198, in parse
    p["style"], p.text, page_width
    ~^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'style'
Traceback (most recent call last):
  File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 48, in parse_document
    return_dict, _ = ingestor_api.ingest_document(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 37, in ingest_document
    ingestor = pdf_ingestor.PDFIngestor(doc_location, parse_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 35, in __init__
    blocks, _block_texts, _sents, _file_data, result, page_dim, num_pages = parse_blocks(
                                                                            ^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 176, in parse_blocks
    parsed_doc = visual_ingestor.Doc(pages, ignore_blocks, render_format)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 117, in __init__
    self.parse(pages)
  File "/app/nlm_ingestor/ingestor/visual_ingestor/visual_ingestor.py", line 198, in parse
    p["style"], p.text, page_width
    ~^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'style'
```   
   
## Steps to reproduce:   
(tested on linux server)
 - docker pull ghcr.io/nlmatics/nlm-ingestor:latest
 - docker run -p 5010:5001 ghcr.io/nlmatics/nlm-ingestor   
```
from llmsherpa.readers import LayoutPDFReader
llmsherpa_api_url = "https://my-url/api/parseDocument?renderFormat=all"

#both mehtods, local and online will produce the same error
pdf_url = "https://arxiv.org/pdf/1910.13461.pdf"
pdf_url = "./arxiv.org/pdf/1910.13461.pdf"


pdf_reader = LayoutPDFReader(llmsherpa_api_url)
doc = pdf_reader.read_pdf(pdf_url)

 ```

**Comment by eburnette** [comment]
v0.1.8 and v0.1.7 have this problem for me. v0.1.6 works fine.

**Comment by shshnk158** [comment]
Hey @RaphSte did it work for you. If so, can you update me how?

**Comment by aleksvercau** [comment]
Same issue here, latest version has an issue.

**Comment by RaphSte** [comment]
> Hey @RaphSte did the latest version work for you. If so, can you update me how?

hey, @shshnk158, no, it diddn't work for me. I'll use v0.1.6 for now.

**Comment by shshnk158** [comment]
Yes v0.1.6 is working fine, but it comes with `tika-server-standard-nlm-modified-2.4.1_v6.jar`, I wanted to try out with the latest jar file `[tika-server-standard-nlm-modified-2.9.2_v1.jar](https://github.com/nlmatics/nlm-ingestor/blob/main/jars/tika-server-standard-nlm-modified-2.9.2_v1.jar)`  any suggestions @ansukla

**Comment by thenicekat** [comment]
yes, facing this issue on v0.1.7 and v0.1.8

**Comment by vitorhirota** [comment]
The issue is because paragraphs are missing metadata. PR #70 solves this issue. 

While not merged, you can use it locally with `git fetch origin pull/70/head:PR70` and `git switch PR70`

**Comment by rednag** [comment]
I'm facing the same issue, trying now to build the container with PR70.

**Comment by rednag** [comment]
Container build fails with "Failed to build pandas"

**Comment by vitorhirota** [comment]
@rednag PR #73 is related, but in my case I just updated requirements.txt to have pandas >= 1.24

https://github.com/nlmatics/nlm-ingestor/blob/465e6a1a72619015d194d92ca290176b87f1afe7/requirements.txt#L13

**Comment by heyalistair** [comment]
I can confirm I can building the docker image PR #70, with `pandas>=1.2.4` works and the container does not show the KeyError. Thanks!

**Comment by jamesvillarrubia** [comment]
Sorry, this one's on me.  First PR was massive code refresh on top of the latest Tika and I missed some key elements that my tests missed.  Second PR should resolve it, but waiting on @ansukla or someone to merge here.

**Comment by fede-bello** [comment]
> The issue is because paragraphs are missing metadata. PR #70 solves this issue.
> 
> While not merged, you can use it locally with `git fetch origin pull/70/head:PR70` and `git switch PR70`

I've switched branches but I'm still facing the same

**Comment by faizanahmad3** [comment]
same problem with me. when i run with docx file it run perfectly fine, but gives the same error when use a pdf file.

**Comment by ddose-inferyx** [comment]
> v0.1.8 and v0.1.7

are you talking about nlm-ingestor version. I cant see v0.1.6 there

**Comment by RaphSte** [comment]
> > v0.1.8 and v0.1.7
> 
> are you talking about nlm-ingestor version. I cant see v0.1.6 there

@ddose-inferyx yes, this is about the nlm ingestor version. You can either pull the image directly (see ![here](https://github.com/nlmatics/nlm-ingestor/pkgs/container/nlm-ingestor)) or build it yourself selecting the tag ![v0.1.6](https://github.com/nlmatics/nlm-ingestor/tree/v0.1.6)   
I diddn't try building it myself though. I just pulled the image directly and it worked for me.

**Comment by ddose-inferyx** [comment]
> v0.1.8 and v0.1.7 have this problem for me. v0.1.6 works fine.

Thanks! @RaphSte , It started working for me as I used -**http://localhost:5010/api/parseDocument?renderFormat=all&applyOcr=yes&useNewIndentParser=yes.** Using "**NewIndentParser=yes.**" will also work with the latest.

**Comment by irash03** [comment]
> Here's the docker image I'm using with everything baked in: `jamesmtc/nlm-ingestor`

`docker pull ghcr.io/jamesmtc/nlm-ingestor` 

Error response from daemon: Head "https://ghcr.io/v2/jamesmtc/nlm-ingestor/manifests/latest": denied

**Comment by ddose-inferyx** [comment]
Thank you so much. Everything is working fine with this.

-Dipak

**Comment by ansukla** [comment]
Merging changes from @jamesvillarrubia. Apologies for the delay. Thanks James for putting together the fix. Feel free to send me a note on LinkedIn if something needs attention.
